# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f71\u7247\u540d\u79f0')),
                ('list_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f71\u7247\u7c7b\u578b')),
                ('vod_actor', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5f71\u7247\u6f14\u5458')),
                ('vod_year', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e0a\u6620\u5e74\u4efd')),
                ('vod_data', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e0a\u6620\u65e5\u671f')),
                ('vod_addtime', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('vod_continu', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5f71\u7247\u72b6\u6001')),
                ('vod_pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5f71\u7247\u56fe\u7247')),
                ('vod_director', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5f71\u7247\u5bfc\u6f14')),
                ('vod_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5f71\u7247\u8bed\u8a00')),
                ('vod_area', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5f71\u7247\u5730\u533a')),
                ('vod_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u64ad\u653e\u5730\u5740')),
                ('vod_content', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5267\u60c5\u4ecb\u7ecd')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u7535\u5f71\u4fe1\u606f',
                'verbose_name_plural': '\u7535\u5f71\u4fe1\u606f',
            },
        ),
    ]
